server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率值介于0到1之间，1表示全部采样

#配置Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #Eureka实例名:端口号  也就是Eureka服务端service-url:配置的地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: order
    prefer-ip-address: true