#服务器端口配置
server:
  port: 8001

#数据源的配置
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

#mybaits配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.minlh.sprigncloud.entities

#开启调试模式
#debug: true

#配置Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #Eureka实例名:端口号  也就是Eureka服务端service-url:配置的地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

