server:
  port: 8802

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit:  # 表示定义的名称 ，用于binding整合
          type: rabbit  # 消息组件类型
          environment:  # 设置 rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.0.174
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange # 表示使用的Exchange名称定义
          content-type: application/json # 设置消息的类型，本次为json,文本则设置“text/plain”
          #binder: defaultRabbit #设置要丙丁的消息服务的具体设置
          group: minlhA #自定义分组

#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔
    lease-expiration-duration-in-seconds: 10 # 如果现在超过了5秒的间隔
    instance-id: receive-8802.com # 在信息列表里显示主机名称
    prefer-ip-address: true # 访问路径变为ip地址